// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWJdsL3AQox3MKtPO61x1lbCtt39HmXA',
    appId: '1:476342324498:web:42c86a4e18c4b0fb7077cb',
    messagingSenderId: '476342324498',
    projectId: 'fir-auth-abcb2',
    authDomain: 'fir-auth-abcb2.firebaseapp.com',
    storageBucket: 'fir-auth-abcb2.appspot.com',
    measurementId: 'G-9NQD597KZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkq6eiTA4TZDDwBB1_X2bUpwtCLtAJrk',
    appId: '1:476342324498:android:cac93652fb3dd7c07077cb',
    messagingSenderId: '476342324498',
    projectId: 'fir-auth-abcb2',
    storageBucket: 'fir-auth-abcb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wKc7M7g4erzpcD5T35E2pCaegoye_aQ',
    appId: '1:476342324498:ios:93cb3f23246d91767077cb',
    messagingSenderId: '476342324498',
    projectId: 'fir-auth-abcb2',
    storageBucket: 'fir-auth-abcb2.appspot.com',
    iosBundleId: 'com.example.radioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wKc7M7g4erzpcD5T35E2pCaegoye_aQ',
    appId: '1:476342324498:ios:15abc0436f8fba907077cb',
    messagingSenderId: '476342324498',
    projectId: 'fir-auth-abcb2',
    storageBucket: 'fir-auth-abcb2.appspot.com',
    iosBundleId: 'com.example.radioApp.RunnerTests',
  );
}
